### ISSUE TITLE
Device confirmation?

### ISSUE THREAD

**Issue by jamesbr3** [NabuCasa/pycognito#214]
Hi,
(great library by the way!)

Are there any plans to add device confirmation support into pycognito? specifically, so that the boto3 `confirm_device` and `update_device_status` are supported? This would then allow device-based authentication (i.e. with a token) once the initial user authentication has passed.

I'm working on adding this support to my own copy of this library. If I succeed, would a PR be of interest?

thanks
James

**Comment by arshvimal** [comment]
Added in PR [#216](https://github.com/pvizeli/pycognito/pull/216)
